#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Feb 15 15:41:36 2024

@author: Estudiante
"""


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # Para graficar series multiples
from   matplotlib import ticker   # Para agregar separador de miles
import seaborn as sns           # Para graficar histograma


carpeta = ""


# Cargamos dataset CheetahRegion
ventasPorRegion= pd.read_csv(carpeta+"ventasPorRegion.csv")    

fig, ax = plt.subplots()

ax.pie(data=ventasPorRegion, x='Porcentaje')



# Genera el grafico de barras torta (mejorando la informacion mostrada)
fig, ax = plt.subplots()

ax.set_title('Ventas por Region')
ax.set_xlim(0,10.9)
ax.set_ylim(0,250)
ax.set_xticks(range(1,11,1)) 

plt.rcParams['font.family'] = 'sans-serif'           
plt.rcParams['axes.spines.left']  = False       # Remueve linea derecha  del recuadro
plt.rcParams['font.size'] = 9.0
ax.pie(data=ventasPorRegion, 
       x='Porcentaje', 
       labels='Region',          # Etiquetas
       autopct='%1.2f%%',       # porcentajes
       colors=['dodgerblue',
               'purple',
               'gold',
               'slateblue']       
       )
